language: python

env:
  # earliest and latest supported; last release of every year; 14.0 for txi2p.plugins
  - TWISTED=Twisted==10.1
  - TWISTED=Twisted==10.2
  - TWISTED=Twisted==11.1
  - TWISTED=Twisted==12.3
  - TWISTED=Twisted==13.2
  - TWISTED=Twisted==14.0
  - TWISTED=Twisted==15.2
  - TWISTED=Twisted==16.4
  - TWISTED=https://github.com/twisted/twisted.git

python:
  - 2.7
  - pypy

matrix:
  allow_failures:
    # pypy is a bit sporadic
    - python: pypy

install:
  - pip install $TWISTED coveralls
  - pip install -r requirements.txt

script: coverage run $(which trial) txi2p
after_success: "coveralls"
